index.js: Cannot make config const due to re-assignment if config exists
node_modules/selenium-cucumber-es6/index.js:37
    config = Object.assign(config, require(configFileName));
           ^

TypeError: Assignment to constant variable.